#-------------------------------------------------
#
# Project created by QtCreator 2011-07-22T19:04:15
#
#-------------------------------------------------

QT       += core

QT       -= gui

QT += network

TARGET = jcpp
CONFIG   += console
CONFIG   -= app_bundle

DEFINES += JCPP_LIBRARY

TEMPLATE = lib

LIBS += -lws2_32

INCLUDEPATH += \
        src/main/cpp/jcpp/ \
	src/main/cpp/jcpp/lang \
	src/main/cpp/jcpp/io \
	src/main/cpp/jcpp/io/impl \
	src/main/cpp/jcpp/util \
        src/main/cpp/jcpp/util/concurrent \
	src/main/cpp/jcpp/lang/exception \
	src/main/cpp/jcpp/lang/reflect \
        src/main/cpp/jcpp/rmi/ \
        src/main/cpp/jcpp/rmi/server \
        src/main/cpp/jcpp/rmi/server/impl \
	src/main/cpp/jcpp/rmi/server/impl/gateway \
        src/main/cpp/jcpp/rmi/server/impl/transport \
        src/main/cpp/jcpp/rmi/server/impl/connection \
        src/main/cpp/jcpp/rmi/server/impl/connection/serialization \
        src/main/cpp/jcpp/net \
        src/main/cpp/jcpp/security \

SOURCES += \
    src/main/cpp/jcpp/lang/JClass.cpp \
    src/main/cpp/jcpp/lang/JClassLoader.cpp \
    src/main/cpp/jcpp/lang/JObject.cpp \
    src/main/cpp/jcpp/lang/reflect/JMethod.cpp \
    src/main/cpp/jcpp/lang/reflect/JProxy.cpp \
    src/main/cpp/jcpp/lang/reflect/JInvocationHandler.cpp \
    src/main/cpp/jcpp/lang/reflect/JField.cpp \
    src/main/cpp/jcpp/lang/exception/JNullPointerException.cpp \
    src/main/cpp/jcpp/lang/exception/JIndexOutOfBoundsException.cpp \
    src/main/cpp/jcpp/lang/exception/JException.cpp \
    src/main/cpp/jcpp/lang/JString.cpp \
    src/main/cpp/jcpp/lang/JEnum.cpp \
    src/main/cpp/jcpp/util/JArrayList.cpp \
    src/main/cpp/jcpp/io/JSerializable.cpp \
    src/main/cpp/jcpp/util/JHashtable.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveBoolean.cpp \
    src/main/cpp/jcpp/lang/JBoolean.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveByte.cpp \
    src/main/cpp/jcpp/lang/JByte.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveChar.cpp \
    src/main/cpp/jcpp/lang/JChar.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveDouble.cpp \
    src/main/cpp/jcpp/lang/JDouble.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveFloat.cpp \
    src/main/cpp/jcpp/lang/JFloat.cpp \
    src/main/cpp/jcpp/lang/JPrimtiveInt.cpp \
    src/main/cpp/jcpp/lang/JInteger.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveLong.cpp \
    src/main/cpp/jcpp/lang/JLong.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveShort.cpp \
    src/main/cpp/jcpp/lang/JShort.cpp \
    src/main/cpp/jcpp/io/JInputStream.cpp \
    src/main/cpp/jcpp/io/JDataInputStream.cpp \
    src/main/cpp/jcpp/io/QtDataInputStream.cpp \
    src/main/cpp/jcpp/io/JObjectStreamClass.cpp \
    src/main/cpp/jcpp/io/JObjectInputStream.cpp \
    src/main/cpp/jcpp/lang/exception/JNoSuchFieldException.cpp \
    src/main/cpp/jcpp/lang/exception/JNoSuchMethodException.cpp \
    src/main/cpp/jcpp/lang/exception/JInstantiationException.cpp \
    src/main/cpp/jcpp/lang/exception/JClassNotFoundException.cpp \
    src/main/cpp/jcpp/lang/JNumber.cpp \
    src/main/cpp/jcpp/lang/exception/JIllegalArgumentException.cpp \
    src/main/cpp/jcpp/lang/JStackTraceElement.cpp \
    src/main/cpp/jcpp/lang/exception/JThrowable.cpp \
    src/main/cpp/jcpp/lang/exception/JRuntimeException.cpp \
    src/main/cpp/jcpp/io/JUTFDataFormatException.cpp \
    src/main/cpp/jcpp/io/JIOException.cpp \
    src/main/cpp/jcpp/io/JEOFException.cpp \
    src/main/cpp/jcpp/lang/JPrimitiveArray.cpp \
    src/main/cpp/jcpp/io/impl/SerialCallbackContext.cpp \
    src/main/cpp/jcpp/io/impl/HandleTable.cpp \
    src/main/cpp/jcpp/io/impl/HandleList.cpp \
    src/main/cpp/jcpp/io/impl/BlockDataInputStream.cpp \
    src/main/cpp/jcpp/io/JObjectStreamException.cpp \
    src/main/cpp/jcpp/io/JInvalidClassException.cpp \
    src/main/cpp/jcpp/lang/exception/JError.cpp \
    src/main/cpp/jcpp/lang/exception/JVirtualMachineError.cpp \
    src/main/cpp/jcpp/lang/exception/JInternalError.cpp \
    src/main/cpp/jcpp/io/JStreamCorruptedException.cpp \
    src/main/cpp/jcpp/io/JOptionalDataException.cpp \
    src/main/cpp/jcpp/io/JNotActiveException.cpp \
    src/main/cpp/jcpp/lang/exception/JIllegalStateException.cpp \
    src/main/cpp/jcpp/lang/exception/JUnsupportedOperationException.cpp \
    src/main/cpp/jcpp/lang/exception/JClassCastException.cpp \
    src/main/cpp/jcpp/io/JOutputStream.cpp \
    src/main/cpp/jcpp/io/JDataOutputStream.cpp \
    src/main/cpp/jcpp/io/impl/BlockDataOutputStream.cpp \
    src/main/cpp/jcpp/io/impl/OutputHandleTable.cpp \
    src/main/cpp/jcpp/io/JObjectOutputStream.cpp \
    src/main/cpp/jcpp/io/JObjectStreamField.cpp \
    src/main/cpp/jcpp/lang/JVoid.cpp \
    src/main/cpp/jcpp/io/JExternalizable.cpp \
    src/main/cpp/jcpp/io/JNotSerializableException.cpp \
    src/main/cpp/jcpp/io/QtDataOutputStream.cpp \
    src/main/cpp/jcpp/lang/JInterface.cpp \
    src/main/cpp/jcpp/lang/reflect/JAccessibleObject.cpp \
    src/main/cpp/jcpp/lang/reflect/JPackage.cpp \
    src/main/cpp/jcpp/io/JIO.cpp \
    src/main/cpp/jcpp/lang/JLANG.cpp \
    src/main/cpp/jcpp/lang/reflect/JREFLECT.cpp \
    src/main/cpp/jcpp/util/JUTIL.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JAddress.cpp \
    src/main/cpp/jcpp/util/JCollection.cpp \
    src/main/cpp/jcpp/util/JList.cpp \
    src/main/cpp/jcpp/util/JAbstractCollection.cpp \
    src/main/cpp/jcpp/util/JAbstractList.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JRoute.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayInputStream.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayOutputStream.cpp \
    src/main/cpp/jcpp/net/JInetAddress.cpp \
    src/main/cpp/jcpp/net/JSocket.cpp \
    src/main/cpp/jcpp/net/JNET.cpp \
    src/main/cpp/jcpp/rmi/JRMI.cpp \
    src/main/cpp/jcpp/rmi/server/impl/JIMPL.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGATEWAY.cpp \
    src/main/cpp/jcpp/net/JServerSocket.cpp \
    src/main/cpp/jcpp/lang/JRunnable.cpp \
    src/main/cpp/jcpp/lang/JThread.cpp \
    src/main/cpp/jcpp/lang/QObjectAware.cpp \
    src/main/cpp/jcpp/net/JInet4Address.cpp \
    src/main/cpp/jcpp/net/JInet6Address.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JEndPoint.cpp \
    src/main/cpp/jcpp/util/concurrent/JExecutor.cpp \
    src/main/cpp/jcpp/util/concurrent/JCallable.cpp \
    src/main/cpp/jcpp/util/concurrent/JExecutorService.cpp \
    src/main/cpp/jcpp/util/concurrent/JFuture.cpp \
    src/main/cpp/jcpp/util/concurrent/JRunnableFuture.cpp \
    src/main/cpp/jcpp/util/concurrent/JAbstractExecutorService.cpp \
    src/main/cpp/jcpp/util/concurrent/JThreadPoolExecutor.cpp \
    src/main/cpp/jcpp/util/concurrent/JFutureTask.cpp \
    src/main/cpp/jcpp/util/concurrent/JDelayed.cpp \
    src/main/cpp/jcpp/util/concurrent/JScheduledFuture.cpp \
    src/main/cpp/jcpp/util/concurrent/JScheduledExecutorService.cpp \
    src/main/cpp/jcpp/util/concurrent/JScheduledThreadPoolExecutor.cpp \
    src/main/cpp/jcpp/util/concurrent/JCONCURRENT.cpp \
    src/main/cpp/jcpp/util/JTimerTask.cpp \
    src/main/cpp/jcpp/util/JTimer.cpp \
    src/main/cpp/jcpp/lang/JSystem.cpp \
    src/main/cpp/jcpp/util/concurrent/JRunnableScheduledFuture.cpp \
    src/main/cpp/jcpp/util/concurrent/JScheduledFutureTask.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JITransportRouter.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTransportRouter.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JConnection.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JConnections.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTRANSPORT_PACKAGE.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTransport.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JITransportDispatcher.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JConnectionHeaderReader.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayConfiguration.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewaySocketFactory.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JIGatewaySocket.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewaySocket.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayServerSocket.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayCompressionInputStream.cpp \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayCompressionOutputStream.cpp \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTransportConfiguration.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectPointer.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionConfiguration.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionException.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/IGC.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCClient.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCClientListener.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIInvocationExceptionHandler.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIInvocationListener.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JILifecycle.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JINotExportedObjectListener.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JINotSerializableObjectHandler.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JDefaultNotSerializableObjectHandler.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JNullNotSerializableObjectHandler.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIRegistry.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIServer.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectInformation.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectHandler.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectInformations.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JRegistry.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JServer.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JInvoker.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionInputStream.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionOutputStream.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGC.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGCClient.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGCEndPointInfo.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGCClientEndPointInfo.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionTransportDispatcher.cpp \
    src/main/cpp/jcpp/rmi/server/JSERVER_PACKAGE.cpp \
    src/main/cpp/jcpp/security/MD5.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JMethodDigester.cpp \
    src/main/cpp/jcpp/lang/QObjectHolder.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JCONNECTION_PACKAGE.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JCONNECTION_SERIALIZATION_PACKAGE.cpp \
    src/main/cpp/jcpp/JCPP_PACKAGE.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIRegistryProxy.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCProxy.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCClientProxy.cpp \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIServerProxy.cpp \
    src/main/cpp/jcpp/io/JObjectStreamConstants.cpp \
    src/main/cpp/jcpp/io/JFilterInputStream.cpp \
    src/main/cpp/jcpp/io/JFilterOutputStream.cpp \
    src/main/cpp/jcpp/io/JBufferedInputStream.cpp \
    src/main/cpp/jcpp/io/JBufferedOutputStream.cpp \
    src/main/cpp/jcpp/lang/JIterable.cpp \
    src/main/cpp/jcpp/util/JIterator.cpp \
    src/main/cpp/jcpp/util/JListIterator.cpp \
    src/main/cpp/jcpp/util/JRandomAccess.cpp \
    src/main/cpp/jcpp/lang/JCloneable.cpp \
    src/main/cpp/jcpp/util/JNoSuchElementException.cpp \
    src/main/cpp/jcpp/util/JConcurrentModificationException.cpp \
    src/main/cpp/jcpp/util/JVector.cpp \
    src/main/cpp/jcpp/util/JEnumeration.cpp \
    src/main/cpp/jcpp/lang/exception/JArrayIndexOutOfBoundsException.cpp \
    src/main/cpp/jcpp/util/JCollections.cpp \
    src/main/cpp/jcpp/lang/exception/JCloneNotSupportedException.cpp \
    src/main/cpp/jcpp/lang/JComparable.cpp \
    src/main/cpp/jcpp/util/JSet.cpp \
    src/main/cpp/jcpp/util/JAbstractSet.cpp \
    src/main/cpp/jcpp/util/JHashSet.cpp \
    src/main/cpp/jcpp/util/JMap.cpp \
    src/main/cpp/jcpp/util/JAbstractMap.cpp \
    src/main/cpp/jcpp/util/JHashMap.cpp \
    src/main/cpp/jcpp/util/JDictionary.cpp \
    src/main/cpp/jcpp/io/JInvalidObjectException.cpp \
    src/main/cpp/jcpp/util/JComparator.cpp \
    src/main/cpp/jcpp/util/JQueue.cpp \
    src/main/cpp/jcpp/util/JAbstractQueue.cpp \
    src/main/cpp/jcpp/lang/JThreadLocal.cpp \
    src/main/cpp/jcpp/util/JIdentityHashMap.cpp
    
    
HEADERS += \
    src/main/cpp/jcpp/lang/JClass.h \
    src/main/cpp/jcpp/lang/JClassLoader.h \
    src/main/cpp/jcpp/lang/JObject.h \
    src/main/cpp/jcpp/lang/reflect/JMethod.h \
    src/main/cpp/jcpp/lang/reflect/JProxy.h \
    src/main/cpp/jcpp/lang/reflect/JInvocationHandler.h \
    src/main/cpp/jcpp/lang/reflect/JField.h \
    src/main/cpp/jcpp/lang/exception/JNullPointerException.h \
    src/main/cpp/jcpp/lang/exception/JIndexOutOfBoundsException.h \
    src/main/cpp/jcpp/lang/exception/JException.h \
    src/main/cpp/jcpp/lang/JString.h \
    src/main/cpp/jcpp/lang/JEnum.h \
    src/main/cpp/jcpp/util/JArrayList.h \
    src/main/cpp/jcpp/io/JSerializable.h \
    src/main/cpp/jcpp/util/JCollection.h \
    src/main/cpp/jcpp/util/JHashtable.h \
    src/main/cpp/jcpp/lang/JPrimitiveBoolean.h \
    src/main/cpp/jcpp/lang/JBoolean.h \
    src/main/cpp/jcpp/lang/JPrimitiveByte.h \
    src/main/cpp/jcpp/lang/JByte.h \
    src/main/cpp/jcpp/lang/JPrimitiveChar.h \
    src/main/cpp/jcpp/lang/JChar.h \
    src/main/cpp/jcpp/lang/JPrimitiveDouble.h \
    src/main/cpp/jcpp/lang/JDouble.h \
    src/main/cpp/jcpp/lang/JPrimitiveFloat.h \
    src/main/cpp/jcpp/lang/JFloat.h \
    src/main/cpp/jcpp/lang/JPrimitiveInt.h \
    src/main/cpp/jcpp/lang/JInteger.h \
    src/main/cpp/jcpp/lang/JPrimitiveLong.h \
    src/main/cpp/jcpp/lang/JLong.h \
    src/main/cpp/jcpp/lang/JPrimitiveShort.h \
    src/main/cpp/jcpp/lang/JShort.h \
    src/main/cpp/jcpp/io/JObjectStreamConstants.h \
    src/main/cpp/jcpp/io/JInputStream.h \
    src/main/cpp/jcpp/io/JDataInputStream.h \
    src/main/cpp/jcpp/io/QtDataInputStream.h \
    src/main/cpp/jcpp/io/JObjectStreamClass.h \
    src/main/cpp/jcpp/io/JObjectInputStream.h \
    src/main/cpp/jcpp/util/Collections.h \
    src/main/cpp/jcpp/lang/exception/JNoSuchFieldException.h \
    src/main/cpp/jcpp/lang/exception/JNoSuchMethodException.h \
    src/main/cpp/jcpp/lang/exception/JInstantiationException.h \
    src/main/cpp/jcpp/lang/exception/JClassNotFoundException.h \
    src/main/cpp/jcpp/lang/JNumber.h \
    src/main/cpp/jcpp/lang/exception/JIllegalArgumentException.h \
    src/main/cpp/jcpp/lang/exception/JThrowable.h \
    src/main/cpp/jcpp/lang/JStackTraceElement.h \
    src/main/cpp/jcpp/lang/exception/JRuntimeException.h \
    src/main/cpp/jcpp/io/JUTFDataFormatException.h \
    src/main/cpp/jcpp/io/JIOException.h \
    src/main/cpp/jcpp/io/JEOFException.h \
    src/main/cpp/jcpp/lang/JPrimitiveArray.h \
    src/main/cpp/jcpp/io/impl/SerialCallbackContext.h \
    src/main/cpp/jcpp/io/impl/HandleTable.h \
    src/main/cpp/jcpp/io/impl/HandleList.h \
    src/main/cpp/jcpp/io/impl/BlockDataInputStream.h \
    src/main/cpp/jcpp/io/JObjectStreamException.h \
    src/main/cpp/jcpp/io/JInvalidClassException.h \
    src/main/cpp/jcpp/lang/exception/JError.h \
    src/main/cpp/jcpp/lang/exception/JVirtualMachineError.h \
    src/main/cpp/jcpp/lang/exception/JInternalError.h \
    src/main/cpp/jcpp/io/JStreamCorruptedException.h \
    src/main/cpp/jcpp/io/JOptionalDataException.h \
    src/main/cpp/jcpp/io/JNotActiveException.h \
    src/main/cpp/jcpp/io/JIO.h \
    src/main/cpp/jcpp/lang/exception/JIllegalStateException.h \
    src/main/cpp/jcpp/lang/exception/JUnsupportedOperationException.h \
    src/main/cpp/jcpp/lang/exception/JClassCastException.h \
    src/main/cpp/jcpp/io/JOutputStream.h \
    src/main/cpp/jcpp/io/JDataOutputStream.h \
    src/main/cpp/jcpp/io/impl/BlockDataOutputStream.h \
    src/main/cpp/jcpp/io/impl/OutputHandleTable.h \
    src/main/cpp/jcpp/io/JObjectOutputStream.h \
    src/main/cpp/jcpp/io/JObjectStreamField.h \
    src/main/cpp/jcpp/lang/JVoid.h \
    src/main/cpp/jcpp/io/JExternalizable.h \
    src/main/cpp/jcpp/io/JNotSerializableException.h \
    src/main/cpp/jcpp/io/QtDataOutputStream.h \
    src/main/cpp/jcpp/lang/Object.h \
    src/main/cpp/jcpp/lang/JInterface.h \
    src/main/cpp/jcpp/lang/reflect/JAccessibleObject.h \
    src/main/cpp/jcpp/lang/reflect/JPackage.h \
    src/main/cpp/jcpp/lang/JLANG.h \
    src/main/cpp/jcpp/lang/reflect/JREFLECT.h \
    src/main/cpp/jcpp/util/JUTIL.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JAddress.h \
    src/main/cpp/jcpp/util/JAbstractList.h \
    src/main/cpp/jcpp/util/JList.h \
    src/main/cpp/jcpp/util/JAbstractCollection.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JRoute.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayInputStream.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayOutputStream.h \
    src/main/cpp/jcpp/net/JSocket.h \
    src/main/cpp/jcpp/net/JInetAddress.h \
    src/main/cpp/jcpp/net/JNET.h \
    src/main/cpp/jcpp/rmi/JRMI.h \
    src/main/cpp/jcpp/rmi/server/impl/JIMPL.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGATEWAY.h \
    src/main/cpp/jcpp/net/JServerSocket.h \
    src/main/cpp/jcpp/lang/JThread.h \
    src/main/cpp/jcpp/lang/JRunnable.h \
    src/main/cpp/jcpp/lang/QObjectAware.h \
    src/main/cpp/jcpp/net/JInet4Address.h \
    src/main/cpp/jcpp/net/JInet6Address.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JEndPoint.h \
    src/main/cpp/jcpp/util/concurrent/JExecutor.h \
    src/main/cpp/jcpp/util/concurrent/JExecutorService.h \
    src/main/cpp/jcpp/util/concurrent/JFuture.h \
    src/main/cpp/jcpp/util/concurrent/JRunnableFuture.h \
    src/main/cpp/jcpp/util/concurrent/JCallable.h \
    src/main/cpp/jcpp/util/concurrent/JAbstractExecutorService.h \
    src/main/cpp/jcpp/util/concurrent/JThreadPoolExecutor.h \
    src/main/cpp/jcpp/util/concurrent/JFutureTask.h \
    src/main/cpp/jcpp/util/concurrent/JDelayed.h \
    src/main/cpp/jcpp/util/concurrent/JScheduledFuture.h \
    src/main/cpp/jcpp/util/concurrent/JScheduledExecutorService.h \
    src/main/cpp/jcpp/util/concurrent/JScheduledThreadPoolExecutor.h \
    src/main/cpp/jcpp/util/concurrent/JCONCURRENT.h \
    src/main/cpp/jcpp/util/JTimer.h \
    src/main/cpp/jcpp/util/JTimerTask.h \
    src/main/cpp/jcpp/lang/JSystem.h \
    src/main/cpp/jcpp/util/concurrent/JRunnableScheduledFuture.h \
    src/main/cpp/jcpp/util/concurrent/JScheduledFutureTask.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JITransportRouter.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTransportRouter.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JConnection.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JConnections.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTRANSPORT_PACKAGE.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTransport.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JITransportDispatcher.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JConnectionHeaderReader.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewaySocketFactory.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayConfiguration.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JIGatewaySocket.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewaySocket.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayServerSocket.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayCompressionInputStream.h \
    src/main/cpp/jcpp/rmi/server/impl/gateway/JGatewayCompressionOutputStream.h \
    src/main/cpp/jcpp/rmi/server/impl/transport/JTransportConfiguration.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectPointer.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionConfiguration.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionException.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGC.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCClient.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCClientListener.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIInvocationExceptionHandler.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIInvocationListener.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JILifecycle.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JINotExportedObjectListener.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JINotSerializableObjectHandler.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JDefaultNotSerializableObjectHandler.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JNullNotSerializableObjectHandler.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIRegistry.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIServer.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectInformation.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectHandler.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JObjectInformations.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JRegistry.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JServer.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JInvoker.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionInputStream.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionOutputStream.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGC.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGCClient.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGCEndPointInfo.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JGCClientEndPointInfo.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JConnectionTransportDispatcher.h \
    src/main/cpp/jcpp/rmi/server/JSERVER_PACKAGE.h \
    src/main/cpp/jcpp/security/MD5.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JMethodDigester.h \
    src/main/cpp/jcpp/lang/QObjectHolder.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JCONNECTION_PACKAGE.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/serialization/JCONNECTION_SERIALIZATION_PACKAGE.h \
    src/main/cpp/jcpp/JCPP_PACKAGE.h \
    src/main/cpp/jcpp/JCPP.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIRegistryProxy.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCProxy.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIGCClientProxy.h \
    src/main/cpp/jcpp/rmi/server/impl/connection/JIServerProxy.h \
    src/main/cpp/jcpp/io/JFilterInputStream.h \
    src/main/cpp/jcpp/io/JFilterOutputStream.h \
    src/main/cpp/jcpp/io/JBufferedInputStream.h \
    src/main/cpp/jcpp/io/JBufferedOutputStream.h \
    src/main/cpp/jcpp/lang/JIterable.h \
    src/main/cpp/jcpp/util/JIterator.h \
    src/main/cpp/jcpp/util/JListIterator.h \
    src/main/cpp/jcpp/util/JRandomAccess.h \
    src/main/cpp/jcpp/lang/JCloneable.h \
    src/main/cpp/jcpp/util/JNoSuchElementException.h \
    src/main/cpp/jcpp/util/JConcurrentModificationException.h \
    src/main/cpp/jcpp/util/JVector.h \
    src/main/cpp/jcpp/util/JEnumeration.h \
    src/main/cpp/jcpp/lang/exception/JArrayIndexOutOfBoundsException.h \
    src/main/cpp/jcpp/util/JCollections.h \
    src/main/cpp/jcpp/lang/exception/JCloneNotSupportedException.h \
    src/main/cpp/jcpp/lang/JComparable.h \
    src/main/cpp/jcpp/util/JSet.h \
    src/main/cpp/jcpp/util/JAbstractSet.h \
    src/main/cpp/jcpp/util/JHashSet.h \
    src/main/cpp/jcpp/util/JMap.h \
    src/main/cpp/jcpp/util/JAbstractMap.h \
    src/main/cpp/jcpp/util/JHashMap.h \
    src/main/cpp/jcpp/util/JDictionary.h \
    src/main/cpp/jcpp/io/JInvalidObjectException.h \
    src/main/cpp/jcpp/util/JComparator.h \
    src/main/cpp/jcpp/util/JQueue.h \
    src/main/cpp/jcpp/util/JAbstractQueue.h \
    src/main/cpp/jcpp/io/JBits.h \
    src/main/cpp/jcpp/lang/JThreadLocal.h \
    src/main/cpp/jcpp/util/JIdentityHashMap.h
    
    
OTHER_FILES += \
    todo.txt
